title = "dnk8n"
baseurl = ""
languagecode = "en"
defaultcontentlanguage = "en"
theme = "hugo-coder"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = ""

[params]
author = "Dean Kayton"
avatarurl = "images/avatar.jpg"
colorscheme = "light"
commit = "https://github.com/luizdepra/hugo-coder/tree/"
custom_css = []
custom_js = []
dateformat = "2006, January 2"
description = "Focusing on a career in Reinforcement Learning"
footercontent = "Continuously learning"
hideCopyright = false
hideCredits = false
info = "Deliberately setting my intention"
keywords = "blog,developer,personal,reinforcement-learning,AI,ML,RL,machine-learning,artificial-intelligence"
maxSeeAlsoItems = 5
rtl = false

[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/dnk8n/"
weight = 1

[[params.social]]
icon = "fab fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/dnk8n/"
weight = 2

[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/dnk8n/"
weight = 3

[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/dnk8n/"
weight = 4

[[params.social]]
icon = "fab fa-medium"
name = "Medium"
url = "https://medium.com/@dnk8n"
weight = 5

[languages]

[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "About"
name = "About"
url = "about/"
weight = 1

[[languages.en.menu.main]]
identifier = "Blog"
name = "Blog"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
identifier = "Series"
name = "Series"
url = "series/"
weight = 3

[[languages.en.menu.main]]
identifier = "Tags"
name = "Tags"
url = "tags/"
weight = 4

[[languages.en.menu.main]]
identifier = "Projects"
name = "Projects"
url = "series/projects/"
weight = 5

[[languages.en.menu.main]]
identifier = "Contact me"
name = "Contact me"
url = "contact/"
weight = 5

[[languages.en.menu.main]]
identifier = "Download CV"
name = "Download CV"
url = "https://gitlab.com/dnk8n/cv/-/jobs/420595289/artifacts/raw/cvs/generic/cv.pdf"

[languages.pt-br]
languagename = ""
title = ""

[languages.pt-br.menu]
main = []

[languages.pt-br.params]
author = ""
description = ""
footercontent = ""
info = ""
keywords = ""

[taxonomies]
category = "categories"
series = "series"
tag = "tags"